name: SuperStrict
on: workflow_dispatch
jobs:
  call-workflow-passing-data:
    uses: 2dengine/sstrict.lua/.github/workflows/validate.yml@main
    uses: 2dengine/sstrict.lua/.github/workflows/scan.lua@main
